<?php

namespace DoctrineORMModule\Proxy\__CG__\ModuleRepositoryModel\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UnitEntity extends \ModuleRepositoryModel\Entity\UnitEntity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function populate($data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function toResponseArray()
    {
        $this->__load();
        return parent::toResponseArray();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getSubject()
    {
        $this->__load();
        return parent::getSubject();
    }

    public function getMatrix()
    {
        $this->__load();
        return parent::getMatrix();
    }

    public function getNames()
    {
        $this->__load();
        return parent::getNames();
    }

    public function addName(\ModuleRepositoryModel\Entity\UnitNameEntity $name)
    {
        $this->__load();
        return parent::addName($name);
    }

    public function getDescriptions()
    {
        $this->__load();
        return parent::getDescriptions();
    }

    public function addDescription(\ModuleRepositoryModel\Entity\UnitDescriptionEntity $description)
    {
        $this->__load();
        return parent::addDescription($description);
    }

    public function getLevel()
    {
        $this->__load();
        return parent::getLevel();
    }

    public function setLevel($level)
    {
        $this->__load();
        return parent::setLevel($level);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getResults()
    {
        $this->__load();
        return parent::getResults();
    }

    public function addResult(\ModuleRepositoryModel\Entity\UnitResultEntity $result)
    {
        $this->__load();
        return parent::addResult($result);
    }

    public function getMetadata()
    {
        $this->__load();
        return parent::getMetadata();
    }

    public function setMetadata($metadata)
    {
        $this->__load();
        return parent::setMetadata($metadata);
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'code', 'level', 'metadata', 'subject', 'names', 'descriptions', 'results', 'contextBehaviours');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}