<?php

namespace DoctrineORMModule\Proxy\__CG__\ModuleRepositoryModel\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MatrixEntity extends \ModuleRepositoryModel\Entity\MatrixEntity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function toResponseArray()
    {
        $this->__load();
        return parent::toResponseArray();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getLanguages()
    {
        $this->__load();
        return parent::getLanguages();
    }

    public function addLanguage(\ModuleRepositoryModel\Entity\DictionaryLanguageEntity $language)
    {
        $this->__load();
        return parent::addLanguage($language);
    }

    public function getLanugageByLocale($locale)
    {
        $this->__load();
        return parent::getLanugageByLocale($locale);
    }

    public function getCompetencyGroups()
    {
        $this->__load();
        return parent::getCompetencyGroups();
    }

    public function addCompetencyGroup(\ModuleRepositoryModel\Entity\CompetencyGroupEntity $competencyGroup)
    {
        $this->__load();
        return parent::addCompetencyGroup($competencyGroup);
    }

    public function getSubjects()
    {
        $this->__load();
        return parent::getSubjects();
    }

    public function addSubject(\ModuleRepositoryModel\Entity\SubjectEntity $subject)
    {
        $this->__load();
        return parent::addSubject($subject);
    }

    public function getContextBehaviours()
    {
        $this->__load();
        return parent::getContextBehaviours();
    }

    public function addContextBehaviour(\ModuleRepositoryModel\Entity\ContextBehaviourEntity $contextBehaviour)
    {
        $this->__load();
        return parent::addContextBehaviour($contextBehaviour);
    }

    public function populate($data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'languages', 'competencyGroups', 'subjects', 'contextBehaviours');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}